version: '3'

services:
  app1:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NAME=app1

  app2:
    build: .
    ports:
      - "8081:8080"
    environment:
      - PORT=8081
      - NAME=app2

  app3:
    build: .
    ports:
      - "8082:8080"
    environment:
      - PORT=8082
      - NAME=app3

  app4:
    build: .
    ports:
      - "8083:8080"
    environment:
      - PORT=8083
      - NAME=app4

  app5:
    build: .
    ports:
      - "8084:8080"
    environment:
      - PORT=8084
      - NAME=app5
